// services/courses-ja.ts — Japanese learner courses (日本語話者向け英語コース)
import { Course } from './courses';

export const JA_COURSES: Course[] = [
  // =====================================================================
  // 1. 英語のきほん — English Basics for Japanese
  // =====================================================================
  {
    id: 'ja-basics',
    icon: '',
    title: '英語のきほん',
    titleEn: 'English Basics',
    desc: 'ゼロから始める英語 — 発音・文法・単語の基礎をしっかり固める',
    level: 'beginner',
    category: 'basics',
    lessons: [
      {
        id: 'ja-basics-1',
        title: '自己紹介',
        titleZh: '自我介紹',
        type: 'speaking',
        minutes: 5,
        content: '英語での自己紹介は、名前・出身・仕事の3つがあれば十分です。\n\n基本パターン：\n• "Hi, I\'m [name]."\n• "I\'m from [place]."\n• "I work as a [job]."\n\n日本語の「よろしくお願いします」にあたる表現：\n• "Nice to meet you."\n• "It\'s a pleasure to meet you."（フォーマル）\n• "Great to meet you!"（カジュアル）',
        vocab: [
          { en: 'introduce', zh: '紹介する', example: 'Let me introduce myself.' },
          { en: 'originally', zh: '出身は', example: 'I\'m originally from Osaka.' },
          { en: 'currently', zh: '現在', example: 'I currently live in Tokyo.' },
          { en: 'position', zh: '役職', example: 'My position is marketing manager.' },
        ],
        practice: { prompt: 'Introduce yourself in 3 sentences — name, where you\'re from, and your job.', zh: '3文で自己紹介 — 名前、出身、仕事。', hint: 'Hi, I\'m ___. I\'m from ___. I work as a ___.' },
        quiz: [
          { q: '"Nice to meet you" means:', qZh: '', opts: ['さようなら', 'はじめまして', 'ありがとう', 'おはよう'], ans: 1, explain: '"Nice to meet you" = はじめまして。' },
          { q: 'How do you say "出身は大阪です" in English?', qZh: '', opts: ['I go to Osaka', 'I\'m from Osaka', 'I like Osaka', 'Osaka is big'], ans: 1 },
          { q: '"Currently" means:', qZh: '', opts: ['昔', '現在', '未来', '時々'], ans: 1 },
        ],
      },
      {
        id: 'ja-basics-2',
        title: '数字・時間・日付',
        titleZh: '數字時間日期',
        type: 'reading',
        minutes: 6,
        content: '英語の数字と時間は日本語と順番が違うので注意！\n\n日付（アメリカ式）：\n• June 17, 2026 → "June seventeenth, twenty twenty-six"\n\n時間：\n• 3:00 → "three o\'clock"\n• 3:15 → "three fifteen" / "quarter past three"\n• 3:30 → "three thirty" / "half past three"\n• 3:45 → "three forty-five" / "quarter to four"\n\n⚠️ 日本人がよく間違えるポイント：\n• 「15分」= fifteen（フィフティーン）≠ fifty（50）\n• 「13」= thirteen ≠ thirty（30）',
        vocab: [
          { en: 'o\'clock', zh: '〜時', example: 'It\'s 7 o\'clock.' },
          { en: 'quarter', zh: '15分', example: 'A quarter past two.' },
          { en: 'half', zh: '30分', example: 'Half past ten.' },
          { en: 'appointment', zh: '予約', example: 'I have an appointment at 3.' },
        ],
        quiz: [
          { q: 'How do you say "3:15" in English?', qZh: '', opts: ['Three fifty', 'Three fifteen', 'Fifteen three', 'Quarter three'], ans: 1 },
          { q: '"Half past seven" = ?', qZh: '', opts: ['6:30', '7:00', '7:30', '8:00'], ans: 2 },
          { q: 'What is "2026" in English?', qZh: '', opts: ['Two zero two six', 'Twenty twenty-six', 'Two thousand twenty-six', 'Both B and C are OK'], ans: 3 },
        ],
      },
      {
        id: 'ja-basics-3',
        title: '発音のコツ① — RとL',
        titleZh: '發音 R/L',
        type: 'listening',
        minutes: 8,
        content: '日本人にとって最大の壁、RとL。\n\nRの発音：\n• 舌を口のどこにもつけない\n• 舌を後ろに引いて、口をすぼめる\n• 「ゥル」のような音\n\nLの発音：\n• 舌の先を前歯の裏につける\n• 「ル」とはっきり発音\n\n練習ペア：\n• right（右／正しい）vs light（光／軽い）\n• rice（ご飯）vs lice（シラミ）\n• road（道）vs load（荷物）\n• pray（祈る）vs play（遊ぶ）',
        vocab: [
          { en: 'right', zh: '右・正しい', example: 'Turn right at the corner.' },
          { en: 'light', zh: '光・軽い', example: 'This bag is very light.' },
          { en: 'rice', zh: 'ご飯', example: 'I eat rice every day.' },
          { en: 'correct', zh: '正しい', example: 'That\'s the correct answer.' },
        ],
        practice: { prompt: 'Read aloud: right, light, rice, lice, road, load, pray, play. Focus on tongue position.', zh: '声に出して読む：right, light, rice, road。舌の位置に集中。' },
        quiz: [
          { q: 'Rの発音で、舌はどこに？', qZh: '', opts: ['前歯の裏につける', '口のどこにもつけない', '上あごの真ん中', '下唇につける'], ans: 1, explain: 'Rは舌をどこにもつけず、後ろに引く。' },
          { q: '"Light" and "right" differ in:', qZh: '', opts: ['L vs R', '母音', '最後の文字', '意味は同じ'], ans: 0 },
        ],
      },
      {
        id: 'ja-basics-4',
        title: '発音のコツ② — THの音',
        titleZh: '發音 TH',
        type: 'listening',
        minutes: 7,
        content: 'THの音は日本語にないので、舌を前歯ではさむ感覚を覚えよう。\n\n無声音 /θ/（息だけ）：\n• think, thank, three, throw, thousand\n\n有声音 /ð/（声を出す）：\n• this, that, the, they, mother\n\n練習文：\n• "I think that this is the best."\n• "Thank you for the three things."\n• "My mother and father are there."',
        vocab: [
          { en: 'think', zh: '考える', example: 'I think so too.' },
          { en: 'thank', zh: '感謝する', example: 'Thank you very much.' },
          { en: 'this', zh: 'これ', example: 'This is delicious.' },
          { en: 'that', zh: 'それ・あれ', example: 'That sounds good.' },
        ],
        practice: { prompt: 'Repeat 5 times: "I think that this is the best thing."', zh: '5回繰り返す："I think that this is the best thing."' },
        quiz: [
          { q: 'THの無声音 /θ/ はどれ？', qZh: '', opts: ['this', 'that', 'think', 'the'], ans: 2, explain: 'think の th は無声音（息だけ）。' },
          { q: '"Thank" の TH発音で舌はどこ？', qZh: '', opts: ['上あご', '前歯ではさむ', '唇', 'ノド'], ans: 1 },
        ],
      },
      {
        id: 'ja-basics-5',
        title: 'よく使う動詞トップ10',
        titleZh: '常用動詞',
        type: 'vocab',
        minutes: 8,
        content: 'この10個の動詞で日常会話の80%がカバーできます。\n\n1. be（〜である）→ I am happy.\n2. have（持っている）→ I have a question.\n3. do（する）→ What do you do?\n4. say（言う）→ What did you say?\n5. get（得る／なる）→ I get up at 7.\n6. make（作る）→ She makes coffee.\n7. go（行く）→ Let\'s go!\n8. know（知っている）→ I don\'t know.\n9. take（取る／乗る）→ Take your time.\n10. see（見る／会う）→ See you later!',
        vocab: [
          { en: 'be', zh: '〜である', example: 'I am a student.' },
          { en: 'have', zh: '持っている', example: 'I have two cats.' },
          { en: 'get', zh: '得る・なる', example: 'I got a new job.' },
          { en: 'take', zh: '取る・乗る', example: 'I take the train to work.' },
        ],
        practice: { prompt: 'Use 5 of the verbs above to describe your daily routine.', zh: '上の動詞を5つ使って日常生活を説明。' },
        quiz: [
          { q: '"I get up at 7" — "get up" の意味は？', qZh: '', opts: ['寝る', '起きる', '食べる', '歩く'], ans: 1 },
          { q: '"Take your time" の意味は？', qZh: '', opts: ['時間を守れ', '急げ', 'ゆっくりどうぞ', '時間を取れ'], ans: 2 },
          { q: 'Which verb means "知っている"?', qZh: '', opts: ['go', 'see', 'know', 'make'], ans: 2 },
        ],
      },
    ],
  },

  // =====================================================================
  // 2. ビジネス英語 — Business English for Japanese
  // =====================================================================
  {
    id: 'ja-business',
    icon: '',
    title: 'ビジネス英語',
    titleEn: 'Business English',
    desc: '会議・メール・プレゼン・交渉 — 職場で即使えるビジネス英語',
    level: 'intermediate',
    category: 'business',
    lessons: [
      {
        id: 'ja-business-1',
        title: '英文メールの書き方',
        titleZh: '商務Email',
        type: 'reading',
        minutes: 8,
        content: 'ビジネスメールの基本構成：\n\n① 件名：簡潔に\n• "Meeting request: Q3 Review"\n• "Question about invoice #1234"\n\n② 宛名：\n• Dear Mr. Tanaka,\n• Dear Ms. Suzuki,\n• Hi Team,（カジュアル）\n\n③ 本文：結論を先に\n• "I\'m writing to..."\n• "This is regarding..."\n\n④ 結び：\n• "Best regards,"\n• "Kind regards,"\n• "Thank you,"\n\n⚠️ 日本式の「いつもお世話になっております」→ 英語にはない！\n代わりに："I hope you\'re doing well." や "Thank you for your continued support."',
        vocab: [
          { en: 'regarding', zh: '〜に関して', example: 'Regarding our meeting next week...' },
          { en: 'attached', zh: '添付', example: 'Please see the attached file.' },
          { en: 'appreciate', zh: '感謝する', example: 'I appreciate your quick response.' },
          { en: 'follow up', zh: 'フォローアップ', example: 'I will follow up on this.' },
          { en: 'in advance', zh: '事前に', example: 'Thank you in advance.' },
        ],
        quiz: [
          { q: '最もフォーマルな書き出しは？', qZh: '', opts: ['Hey!', 'Dear Mr. Tanaka,', 'Hi,', 'Yo'], ans: 1 },
          { q: '"Please see the attached file" の "attached" は？', qZh: '', opts: ['攻撃', '添付', '出席', '接続'], ans: 1 },
          { q: '日本式の「お世話になっております」の代わりになる表現は？', qZh: '', opts: ['Thank you for your support', 'Sorry', 'Hello', 'Goodbye'], ans: 0 },
        ],
      },
      {
        id: 'ja-business-2',
        title: '会議で使えるフレーズ',
        titleZh: '會議句型',
        type: 'speaking',
        minutes: 10,
        content: '英語の会議では「沈黙＝参加していない」と見なされます。積極的に発言しましょう。\n\n会議の始め方：\n• "Let\'s get started."\n• "Thank you all for joining today."\n\n意見を述べる：\n• "In my opinion..."\n• "From my perspective..."\n• "I\'d like to add that..."\n\n賛成する：\n• "I agree with that point."\n• "That\'s a good idea."\n\n反対する（丁寧に）：\n• "I see your point, but..."\n• "That\'s one way to look at it. Another perspective is..."\n\n質問する：\n• "Could you elaborate on that?"\n• "What do you mean by...?"',
        vocab: [
          { en: 'agenda', zh: '議題', example: 'Let\'s go through the agenda.' },
          { en: 'minutes', zh: '議事録', example: 'I\'ll take the minutes.' },
          { en: 'proposal', zh: '提案', example: 'I have a proposal to make.' },
          { en: 'consensus', zh: '合意', example: 'Let\'s reach a consensus.' },
          { en: 'action item', zh: 'アクション項目', example: 'What are the action items?' },
        ],
        practice: { prompt: 'Lead a short team meeting about a new project. Start the meeting, share one idea, and ask for opinions.', zh: '3分のミーティングをリード。開始→意見共有→質問。' },
        quiz: [
          { q: '"Let\'s get started" はどんな時に使う？', qZh: '', opts: ['会議を始める時', '会議を終わる時', '休憩する時', '電話する時'], ans: 0 },
          { q: '丁寧に反対する時のフレーズは？', qZh: '', opts: ['No!', 'You\'re wrong', 'I see your point, but...', 'Whatever'], ans: 2 },
          { q: '"Could you elaborate?" の意味は？', qZh: '', opts: ['簡潔に言って', '詳しく説明して', '後で話そう', '無視して'], ans: 1 },
        ],
      },
      {
        id: 'ja-business-3',
        title: '自己PRとエレベーターピッチ',
        titleZh: 'Elevator Pitch',
        type: 'speaking',
        minutes: 8,
        content: 'エレベーターピッチ＝30秒であなたの価値を伝える。日本の転職面接でも必須スキルに。\n\n構成：\n1. Who you are（誰か）\n2. What you do（何をしているか）\n3. What makes you unique（あなたの強み）\n4. What you want（何を求めているか）\n\n例：\n"Hi, I\'m Yuki. I\'m a product designer with 5 years of experience in fintech. I specialize in making complex financial data simple and beautiful. I\'m looking for a role where I can lead design strategy."',
        vocab: [
          { en: 'pitch', zh: '売り込み', example: 'I prepared my elevator pitch.' },
          { en: 'specialize', zh: '専門とする', example: 'I specialize in UX design.' },
          { en: 'background', zh: '経歴', example: 'My background is in engineering.' },
          { en: 'passionate', zh: '情熱的', example: 'I\'m passionate about education.' },
        ],
        practice: { prompt: 'Prepare and deliver a 30-second elevator pitch about yourself.', zh: '30秒の自己PRを作って話す。' },
        quiz: [
          { q: 'エレベーターピッチの長さは？', qZh: '', opts: ['5分', '30秒', '10分', '1時間'], ans: 1 },
          { q: '"I specialize in ___" の意味は？', qZh: '', opts: ['〜に住んでいる', '〜を専門としている', '〜が嫌い', '〜を忘れた'], ans: 1 },
        ],
      },
      {
        id: 'ja-business-4',
        title: '英語プレゼンの組み立て方',
        titleZh: 'Presentation',
        type: 'speaking',
        minutes: 10,
        content: '英語プレゼンの黄金構成「Tell them法」：\n\n① Introduction（導入）\n• "Today, I\'d like to talk about..."\n• "I\'ll cover three main points..."\n\n② Body（本題）\n• "First, let\'s look at..."\n• "Next, I\'d like to discuss..."\n• "Finally, we\'ll explore..."\n\n③ Conclusion（結論）\n• "To sum up..."\n• "In conclusion..."\n\n④ Q&A\n• "I\'d be happy to take your questions."\n• "That\'s a great question."\n\n⚠️ 日本人がやりがちなミス：\n• 前置きが長すぎる → 最初に結論を\n• 声が小さい → 会議室の一番後ろの人に届く声で',
        vocab: [
          { en: 'overview', zh: '概要', example: 'Here\'s a quick overview.' },
          { en: 'key point', zh: '重要ポイント', example: 'The key point is...' },
          { en: 'data', zh: 'データ', example: 'The data shows that...' },
          { en: 'summary', zh: 'まとめ', example: 'In summary...' },
        ],
        practice: { prompt: 'Give a 2-minute presentation on: "Why I recommend my favorite product."', zh: '2分間プレゼン：「お気に入りの製品をおすすめする理由」' },
        quiz: [
          { q: 'プレゼンの導入で言うべきことは？', qZh: '', opts: ['自分の趣味', '今日話す内容の概要', '天気の話', '長い前置き'], ans: 1 },
          { q: '"In conclusion" はどこで使う？', qZh: '', opts: ['導入', '本題', '結論', '質疑応答'], ans: 2 },
        ],
      },
      {
        id: 'ja-business-5',
        title: '海外出張・電話会議',
        titleZh: '出差電話',
        type: 'speaking',
        minutes: 8,
        content: '海外出張と英語での電話会議に必須の表現。\n\n空港で：\n• "I\'d like to check in."\n• "Window seat, please."\n\n電話会議：\n• "Can everyone hear me?"\n• "You\'re breaking up."（音声が途切れている）\n• "Let me share my screen."\n\nスモールトーク（日本人が苦手な雑談）：\n• "How was your weekend?"\n• "Did you watch the game last night?"\n• "How\'s the weather over there?"\n\n⚠️ 日本人あるある：いきなり本題に入る → まず30秒雑談を。',
        vocab: [
          { en: 'check in', zh: 'チェックイン', example: 'I checked in online.' },
          { en: 'boarding pass', zh: '搭乗券', example: 'Here is your boarding pass.' },
          { en: 'mute', zh: 'ミュート', example: 'You\'re on mute!' },
          { en: 'time zone', zh: 'タイムゾーン', example: 'What time zone are you in?' },
        ],
        quiz: [
          { q: '"You\'re breaking up" の意味は？', qZh: '', opts: ['別れよう', '音声が途切れてる', '壊してる', '解散しよう'], ans: 1 },
          { q: '英語の電話会議でまずすることは？', qZh: '', opts: ['いきなり本題', '少し雑談（スモールトーク）', '無言', 'メールを送る'], ans: 1 },
        ],
      },
    ],
  },

  // =====================================================================
  // 3. 日常英会話 — Daily English for Japanese
  // =====================================================================
  {
    id: 'ja-daily',
    icon: '',
    title: '日常英会話',
    titleEn: 'Daily Conversation',
    desc: '友達との会話・趣味・旅行・レストラン — リアルな日常英語',
    level: 'beginner',
    category: 'basics',
    lessons: [
      {
        id: 'ja-daily-1',
        title: '友達とのカジュアルな会話',
        titleZh: '朋友聊天',
        type: 'speaking',
        minutes: 6,
        content: 'ネイティブの友達ができたときに使えるカジュアル英語。\n\nあいさつ：\n• "Hey, what\'s up?" → 特に意味はない、「やあ」\n• "How\'s it going?" → 「調子どう？」\n• "Long time no see!" → 「久しぶり！」\n\n返事：\n• "Pretty good!"\n• "Not much, you?"\n• "Same old, same old."（相変わらずだよ）\n\n別れ際：\n• "See you later!"\n• "Take care!"\n• "Catch you later!"',
        vocab: [
          { en: 'what\'s up', zh: 'やあ・元気？', example: 'Hey, what\'s up?' },
          { en: 'pretty', zh: 'かなり', example: 'That\'s pretty cool!' },
          { en: 'hang out', zh: '遊ぶ・過ごす', example: 'Want to hang out this weekend?' },
          { en: 'awesome', zh: '最高', example: 'That\'s awesome!' },
        ],
        practice: { prompt: 'Have a casual 1-minute chat: greet, ask how they are, and suggest meeting up.', zh: '1分間のカジュアル会話。挨拶→近況→遊びの誘い。' },
        quiz: [
          { q: '"What\'s up?" の自然な返事は？', qZh: '', opts: ['I am fine thank you', 'Not much, you?', 'Yes I do', 'Goodbye'], ans: 1, explain: '"I am fine thank you" は教科書英語。実際は "Not much" や "Pretty good" が自然。' },
          { q: '"Hang out" の意味は？', qZh: '', opts: ['首を吊る', '外に出る', '一緒に過ごす', '買い物する'], ans: 2 },
        ],
      },
      {
        id: 'ja-daily-2',
        title: 'レストランでの英会話',
        titleZh: '餐廳',
        type: 'speaking',
        minutes: 7,
        content: '海外のレストランで自信を持って注文しよう。\n\n予約：\n• "I have a reservation under the name Suzuki."\n\n注文：\n• "I\'ll have the grilled salmon, please."\n• "Could I get this without onions?"\n\nリクエスト：\n• "Can I have some water, please?"\n• "Excuse me, could we get the bill?"\n\nチップ（日本にはない習慣！）：\n• アメリカ：15-20%\n• イギリス：サービス料込みの場合が多い\n• "Keep the change!"（お釣りはとっておいて）',
        vocab: [
          { en: 'reservation', zh: '予約', example: 'Do you have a reservation?' },
          { en: 'appetizer', zh: '前菜', example: 'Would you like an appetizer?' },
          { en: 'medium rare', zh: 'ミディアムレア', example: 'I\'d like my steak medium rare.' },
          { en: 'check', zh: 'お会計', example: 'Could we get the check please?' },
        ],
        quiz: [
          { q: '"I\'ll have the ___" はどんな時に使う？', qZh: '', opts: ['注文する時', 'お会計の時', '席につく時', '帰る時'], ans: 0 },
          { q: 'アメリカでのチップの相場は？', qZh: '', opts: ['0%', '5%', '15-20%', '50%'], ans: 2 },
        ],
      },
      {
        id: 'ja-daily-3',
        title: '趣味の話で盛り上がる',
        titleZh: '興趣話題',
        type: 'speaking',
        minutes: 7,
        content: '趣味の話は最強のアイスブレイク。自分の「推し」を英語で語ろう。\n\n質問：\n• "What do you do in your free time?"\n• "What are you into lately?"\n• "Are you a fan of...?"\n\n自分の趣味を語る：\n• "I\'m really into photography."\n• "I\'ve been playing guitar for 3 years."\n• "I\'m a big fan of anime."\n\n共感する：\n• "No way, me too!"\n• "That\'s so cool!"\n• "I\'ve always wanted to try that."',
        vocab: [
          { en: 'into', zh: '〜にハマっている', example: 'I\'m really into yoga lately.' },
          { en: 'fan', zh: 'ファン', example: 'I\'m a huge fan of Studio Ghibli.' },
          { en: 'recommend', zh: 'おすすめする', example: 'I highly recommend it.' },
          { en: 'obsessed', zh: '夢中', example: 'I\'m obsessed with this game.' },
        ],
        practice: { prompt: 'Talk about your favorite hobby for 1 minute. What is it, why do you like it, and when did you start?', zh: '自分の趣味について1分間話す。何か、なぜ好きか、いつ始めたか。' },
        quiz: [
          { q: '"I\'m into ___" の意味は？', qZh: '', opts: ['〜の中に入る', '〜にハマっている', '〜が嫌い', '〜を捨てる'], ans: 1 },
          { q: '"What are you into lately?" は何を聞いている？', qZh: '', opts: ['仕事', '最近ハマっていること', '住所', '年齢'], ans: 1 },
        ],
      },
      {
        id: 'ja-daily-4',
        title: 'SNSとチャットの英語',
        titleZh: 'SNS聊天',
        type: 'reading',
        minutes: 6,
        content: 'SNSやチャットでよく使われる省略表現・スラング。\n\nよく使う略語：\n• LOL = Laugh Out Loud（爆笑）\n• OMG = Oh My God（やばい！）\n• TBH = To Be Honest（正直言うと）\n• IDK = I don\'t know\n• BRB = Be Right Back（すぐ戻る）\n• DM = Direct Message\n\n感情表現：\n• "That\'s fire!" = 最高！\n• "No cap" = マジで（嘘じゃない）\n• "Slay!" = 最高にかっこいい！\n• "It\'s giving ___ vibes" = 〜な感じがする',
        vocab: [
          { en: 'LOL', zh: '爆笑', example: 'That joke was so funny LOL.' },
          { en: 'DM', zh: 'ダイレクトメッセージ', example: 'DM me the details.' },
          { en: 'vibe', zh: '雰囲気・感じ', example: 'This cafe has good vibes.' },
          { en: 'TBH', zh: '正直言うと', example: 'TBH I didn\'t like the movie.' },
        ],
        quiz: [
          { q: '"LOL" は何の略？', qZh: '', opts: ['Lots of Love', 'Laugh Out Loud', 'Live On Line', 'Lemon Orange Lime'], ans: 1 },
          { q: '"BRB" の意味は？', qZh: '', opts: ['さようなら', 'すぐ戻る', 'こんにちは', 'ありがとう'], ans: 1 },
          { q: '"That\'s fire!" はどういう意味？', qZh: '', opts: ['火事だ！', '最高！', '暑い！', '危ない！'], ans: 1 },
        ],
      },
      {
        id: 'ja-daily-5',
        title: '旅行先で使えるお願い・質問',
        titleZh: '旅遊問路',
        type: 'speaking',
        minutes: 7,
        content: '海外旅行で絶対に使うフレーズ集。\n\n道を聞く：\n• "Excuse me, how do I get to the station?"\n• "Is it within walking distance?"\n• "Could you show me on the map?"\n\n写真を頼む：\n• "Could you take a picture of us?"\n• "Just press this button."\n\n買い物：\n• "How much is this?"\n• "Do you have this in a different color?"\n• "I\'m just looking, thank you."（見てるだけです）\n\n緊急時：\n• "I need help."\n• "Where is the nearest hospital?"\n• "I lost my passport."',
        vocab: [
          { en: 'direction', zh: '方向', example: 'Could you give me directions?' },
          { en: 'distance', zh: '距離', example: 'Is it a long distance?' },
          { en: 'recommend', zh: 'おすすめ', example: 'What do you recommend?' },
          { en: 'receipt', zh: 'レシート', example: 'Can I have a receipt?' },
        ],
        practice: { prompt: 'You\'re lost in a foreign city. Ask for directions to the nearest train station.', zh: '知らない街で道に迷った。最寄り駅への行き方を聞く。' },
        quiz: [
          { q: '"How do I get to ___?" の意味は？', qZh: '', opts: ['〜はどこで買える？', '〜にどうやって行く？', '〜はいくら？', '〜は何時？'], ans: 1 },
          { q: '"I\'m just looking" — どんな時に使う？', qZh: '', opts: ['店員に話しかけられた時', '道を聞く時', '電話する時', '謝る時'], ans: 0, explain: '買う気がないときに店員をやんわり断る表現。"見てるだけです"。' },
        ],
      },
    ],
  },

  // =====================================================================
  // 4. TOEIC対策 — TOEIC Prep for Japanese
  // =====================================================================
  {
    id: 'ja-toeic',
    icon: '',
    title: 'TOEIC対策',
    titleEn: 'TOEIC Prep',
    desc: 'TOEICスコアアップのコツ — Part 1〜7の頻出パターンと語彙',
    level: 'intermediate',
    category: 'ielts',
    lessons: [
      {
        id: 'ja-toeic-1',
        title: 'TOEIC Part 1 写真描写問題',
        titleZh: 'TOEIC Part1',
        type: 'listening',
        minutes: 8,
        content: 'Part 1は写真を見て、4つの英文から最も適切な説明を選ぶ問題。\n\n頻出パターン：\n• 人が写っている → 動作を表す現在進行形\n  "A woman is typing on a laptop."\n  "The man is reaching for a book."\n\n• 物だけ → 状態や位置を表す受動態・現在完了\n  "The chairs have been arranged in rows."\n  "A ladder is leaning against the wall."\n\n⚠️ ひっかけパターン：\n• 写真に写っていない動作が選択肢にある → 即NG\n• 似ている単語の聞き間違い（walking ≠ working）',
        vocab: [
          { en: 'arrange', zh: '配置する', example: 'The chairs are arranged in a circle.' },
          { en: 'lean', zh: '立てかける', example: 'A bicycle is leaning against the fence.' },
          { en: 'reach for', zh: '〜に手を伸ばす', example: 'He is reaching for a cup.' },
          { en: 'examine', zh: '調べる', example: 'A doctor is examining a patient.' },
        ],
        quiz: [
          { q: 'Part 1で最も多い文法パターンは？', qZh: '', opts: ['現在進行形', '過去形', '未来形', '命令形'], ans: 0 },
          { q: '写真にない動作が選択肢にあったら？', qZh: '', opts: ['正解かも', '即座に除外', '考え直す', '無視'], ans: 1 },
        ],
      },
      {
        id: 'ja-toeic-2',
        title: 'TOEIC Part 2 応答問題',
        titleZh: 'TOEIC Part2',
        type: 'listening',
        minutes: 8,
        content: 'Part 2は発話に対して最も適切な応答を選ぶ問題。\n\n頻出パターン：\n• Wh疑問文 → Yes/Noで答えない！\n  Q: "Where is the meeting room?"\n  A: "It\'s on the third floor."（○）"Yes, it is."（×）\n\n• Yes/No疑問文 → Yes/Noで始める\n  Q: "Did you finish the report?"\n  A: "Yes, I sent it this morning."\n\n• 提案・依頼 → 受諾か断り\n  Q: "Would you like some coffee?"\n  A: "That would be great, thank you."',
        vocab: [
          { en: 'available', zh: '利用可能', example: 'Is the conference room available?' },
          { en: 'finish', zh: '終える', example: 'I haven\'t finished yet.' },
          { en: 'wonder', zh: 'かなと思う', example: 'I wonder if it will rain.' },
        ],
        quiz: [
          { q: '"Where is the exit?" の正しい応答は？', qZh: '', opts: ['Yes, it is', 'No, I don\'t', 'It\'s to your left', 'Thank you'], ans: 2, explain: 'Whereには場所で答える。Yes/NoはNG。' },
          { q: '"Would you like some tea?" → 自然な返事は？', qZh: '', opts: ['I am tea', 'That would be great', 'No I am', 'Where is tea'], ans: 1 },
        ],
      },
      {
        id: 'ja-toeic-3',
        title: 'TOEIC Part 5 文法穴埋め',
        titleZh: 'TOEIC Part5',
        type: 'reading',
        minutes: 10,
        content: 'Part 5は短文の空所補充。品詞の見分けが最重要。\n\n品詞パターン：\n• 冠詞＋___＋名詞 → 形容詞が必要\n  "a ___ report" → detailed / important / annual\n\n• 前置詞＋___ → 名詞または動名詞\n  "before ___" → the meeting / leaving / lunch\n\n• be動詞＋___＋by → 過去分詞（受動態）\n  "was ___ by" → written / built / completed\n\nよく出る接続詞：\n• however / therefore / moreover / nevertheless / although / because / while / despite',
        vocab: [
          { en: 'therefore', zh: 'したがって', example: 'It was raining; therefore, we stayed inside.' },
          { en: 'however', zh: 'しかし', example: 'I like coffee; however, I prefer tea.' },
          { en: 'despite', zh: '〜にもかかわらず', example: 'Despite the rain, we went out.' },
          { en: 'efficiently', zh: '効率的に', example: 'The system works efficiently.' },
        ],
        quiz: [
          { q: '"a ___ report" の空所に入る品詞は？', qZh: '', opts: ['動詞', '形容詞', '副詞', '前置詞'], ans: 1 },
          { q: '"was ___ by" の空所には何が入る？', qZh: '', opts: ['動詞の原形', '過去分詞', '現在分詞', '名詞'], ans: 1 },
          { q: '"___ the rain, we went out" → 空所に入る単語は？', qZh: '', opts: ['Although', 'Because', 'Despite', 'However'], ans: 2, explain: 'Despite + 名詞。Although + SV。' },
        ],
      },
      {
        id: 'ja-toeic-4',
        title: 'TOEIC Part 7 読解問題',
        titleZh: 'TOEIC Part7',
        type: 'reading',
        minutes: 10,
        content: 'Part 7は長文読解。時間配分が合否を分ける。\n\n文章タイプ：\n• Eメール・レター\n• お知らせ・メモ\n• 記事・広告\n• チャット・テキストメッセージ\n\n速読のコツ：\n① 先に設問を読む\n② キーワードを探しながら本文をスキャン\n③ 選択肢の言い換えに注意\n\nよくある言い換え：\n• "purchase" = buy\n• "approximately" = about\n• "due to" = because of\n• "annually" = every year',
        vocab: [
          { en: 'purchase', zh: '購入', example: 'Thank you for your purchase.' },
          { en: 'approximately', zh: '約・およそ', example: 'Approximately 100 people attended.' },
          { en: 'due to', zh: '〜のために', example: 'The event was canceled due to weather.' },
          { en: 'deadline', zh: '締切', example: 'The deadline is next Friday.' },
        ],
        quiz: [
          { q: 'Part 7対策で最も重要なことは？', qZh: '', opts: ['全文を丁寧に読む', '設問を先に読む', '翻訳する', '単語を全部調べる'], ans: 1 },
          { q: '"annually" の言い換えは？', qZh: '', opts: ['every day', 'every week', 'every month', 'every year'], ans: 3 },
        ],
      },
      {
        id: 'ja-toeic-5',
        title: 'TOEIC頻出ビジネス単語100',
        titleZh: 'TOEIC詞彙',
        type: 'vocab',
        minutes: 10,
        content: 'TOEICに頻出するビジネス単語をカテゴリ別に覚えよう。\n\n📊 会議・オフィス：\n• agenda（議題）, minutes（議事録）, conference（会議）\n• deadline（締切）, schedule（予定）, postpone（延期する）\n\n💰 財務・契約：\n• invoice（請求書）, budget（予算）, expense（経費）\n• contract（契約）, negotiate（交渉する）, refund（返金）\n\n🏢 人事・採用：\n• applicant（応募者）, resume（履歴書）, interview（面接）\n• promotion（昇進）, training（研修）, evaluate（評価する）\n\n📧 コミュニケーション：\n• inform（知らせる）, confirm（確認する）, request（依頼する）\n• apologize（謝罪する）, appreciate（感謝する）',
        vocab: [
          { en: 'postpone', zh: '延期する', example: 'The meeting was postponed until Friday.' },
          { en: 'invoice', zh: '請求書', example: 'Please send the invoice by email.' },
          { en: 'refund', zh: '返金', example: 'We will issue a full refund.' },
          { en: 'evaluate', zh: '評価する', example: 'Employees are evaluated twice a year.' },
          { en: 'inform', zh: '知らせる', example: 'Please inform the team about the change.' },
        ],
        quiz: [
          { q: '"postpone" の意味は？', qZh: '', opts: ['延期する', '前倒しする', 'キャンセルする', '開始する'], ans: 0 },
          { q: '"invoice" の意味は？', qZh: '', opts: ['声', '請求書', '招待状', '履歴書'], ans: 1 },
          { q: '"refund" は？', qZh: '', opts: ['再fund', '返金', '投資', '借金'], ans: 1 },
        ],
      },
    ],
  },

  // =====================================================================
  // 5. 猫英語 — Cat Lover's English 🐱
  // =====================================================================
  {
    id: 'ja-cat',
    icon: '🐱',
    title: '猫英語 🐱',
    titleEn: 'Cat Lover\'s English',
    desc: '猫好きのための英語 — 猫カフェ・保護猫・猫自慢を英語で！',
    level: 'beginner',
    category: 'travel',
    lessons: [
      {
        id: 'ja-cat-1',
        title: '猫カフェで使える英語',
        titleZh: '貓Cafe',
        type: 'speaking',
        minutes: 5,
        content: '日本の猫カフェ文化は海外でも大人気！英語で猫カフェを説明してみよう。\n\n猫カフェを説明する：\n• "It\'s a cafe where you can play with cats."\n• "You pay by the hour."\n• "The cats are all rescue cats."（保護猫です）\n\n猫を褒める：\n• "What a cute cat!"\n• "This one is so fluffy!"\n• "Look at those eyes!"\n• "She\'s purring!"（ゴロゴロ言ってる）',
        vocab: [
          { en: 'rescue cat', zh: '保護猫', example: 'All our cats are rescue cats.' },
          { en: 'purr', zh: 'ゴロゴロ鳴く', example: 'The cat is purring on my lap.' },
          { en: 'fluffy', zh: 'ふわふわ', example: 'This fluffy one is my favorite.' },
          { en: 'paw', zh: '肉球', example: 'Look at those tiny paws!' },
        ],
        practice: { prompt: 'You\'re at a cat cafe in Tokyo. Describe the experience to your English-speaking friend.', zh: '東京の猫カフェにいる。英語で猫カフェ体験を友達に説明する。' },
        quiz: [
          { q: '"purr" はどんな音？', qZh: '', opts: ['ニャーニャー', 'ゴロゴロ', 'ワンワン', 'シャー'], ans: 1 },
          { q: '"rescue cat" の意味は？', qZh: '', opts: ['救助猫', '保護猫', '野生猫', '迷子猫'], ans: 1 },
          { q: '"fluffy" の意味は？', qZh: '', opts: ['痩せている', 'ふわふわ', '速い', '小さい'], ans: 1 },
        ],
      },
      {
        id: 'ja-cat-2',
        title: '保護猫活動を英語で説明',
        titleZh: '貓保護',
        type: 'speaking',
        minutes: 6,
        content: '保護猫活動について英語で話せると、海外の猫好きとつながれる！\n\nTNR活動：\n• TNR = Trap, Neuter, Return（捕獲・不妊手術・戻す）\n• "We do TNR to control the stray cat population."\n\n里親募集：\n• "We\'re looking for foster homes."（預かりボランティア募集）\n• "This kitten is up for adoption."（この子猫は里親募集中）\n\n寄付のお願い：\n• "We rely on donations to feed the cats."\n• "Every dollar helps save a cat\'s life."',
        vocab: [
          { en: 'TNR', zh: 'TNR（捕獲・不妊・戻す）', example: 'TNR is the most humane way to help stray cats.' },
          { en: 'foster', zh: '預かる・里親（一時的）', example: 'We need more foster families.' },
          { en: 'adopt', zh: '里親になる', example: 'We adopted two cats last year.' },
          { en: 'donation', zh: '寄付', example: 'Your donation helps feed 50 cats.' },
          { en: 'stray', zh: '野良', example: 'There are many stray cats in this area.' },
        ],
        quiz: [
          { q: '"TNR" の "N" は何？', qZh: '', opts: ['New', 'Neuter（不妊手術）', 'Nice', 'Next'], ans: 1 },
          { q: '"up for adoption" の意味は？', qZh: '', opts: ['飼い主が見つかった', '里親募集中', '逃げた', '病気'], ans: 1 },
        ],
      },
      {
        id: 'ja-cat-3',
        title: '猫自慢を英語で！',
        titleZh: '曬貓',
        type: 'speaking',
        minutes: 5,
        content: 'SNSで自分の猫を英語で紹介しよう！世界中の猫好きとつながれる。\n\n猫の紹介：\n• "This is Mochi. He\'s a 3-year-old tabby."\n• "She\'s a rescue. I found her in a parking lot."\n• "He loves sleeping in cardboard boxes."\n\n猫の性格：\n• "She\'s very shy at first but super affectionate."\n• "He\'s a total troublemaker!"\n• "She follows me everywhere I go."\n\n猫あるある：\n• "He wakes me up at 5am every day for food."\n• "She knocked over my coffee... again."',
        vocab: [
          { en: 'tabby', zh: 'トラ猫', example: 'My tabby has beautiful stripes.' },
          { en: 'affectionate', zh: '愛情深い', example: 'He\'s the most affectionate cat I\'ve ever had.' },
          { en: 'mischievous', zh: 'いたずら好き', example: 'My kitten is so mischievous!' },
          { en: 'cuddle', zh: '抱っこする', example: 'She loves to cuddle on the sofa.' },
        ],
        practice: { prompt: 'Post an Instagram caption in English about your cat (or a cat you know). Include name, personality, and a funny story.', zh: '猫のインスタ投稿を英語で書く。名前・性格・面白いエピソード。' },
        quiz: [
          { q: '"tabby" はどんな猫？', qZh: '', opts: ['白猫', '黒猫', 'トラ猫', '三毛猫'], ans: 2 },
          { q: '"affectionate" の反対は？', qZh: '', opts: ['friendly', 'cold / aloof', 'cute', 'small'], ans: 1 },
        ],
      },
      {
        id: 'ja-cat-4',
        title: '猫の健康・獣医で使う英語',
        titleZh: '貓獸醫',
        type: 'speaking',
        minutes: 7,
        content: '海外で猫を飼う時、獣医さんとの英会話は必須！\n\n症状を伝える：\n• "She hasn\'t been eating for two days."\n• "He\'s been vomiting."\n• "She seems lethargic."（元気がない）\n\n予防接種：\n• "What vaccinations does she need?"\n• "Is she due for a booster shot?"\n\n去勢・避妊：\n• "When should I get him neutered?"\n• "How much does spaying cost?"',
        vocab: [
          { en: 'veterinarian', zh: '獣医', example: 'We need to see a veterinarian.' },
          { en: 'vaccination', zh: '予防接種', example: 'Her vaccinations are up to date.' },
          { en: 'spay / neuter', zh: '避妊／去勢手術', example: 'It\'s important to spay and neuter your pets.' },
          { en: 'symptom', zh: '症状', example: 'What symptoms is she showing?' },
          { en: 'appetite', zh: '食欲', example: 'He\'s lost his appetite.' },
        ],
        quiz: [
          { q: '"lethargic" の意味は？', qZh: '', opts: ['元気いっぱい', '元気がない・だるそう', '怒っている', '走り回っている'], ans: 1 },
          { q: '"spay" と "neuter" の違いは？', qZh: '', opts: ['犬と猫', 'メスの避妊とオスの去勢', '大きい手術と小さい手術', '同じ意味'], ans: 1 },
        ],
      },
      {
        id: 'ja-cat-5',
        title: '猫イベント・譲渡会で交流',
        titleZh: '貓活動',
        type: 'speaking',
        minutes: 6,
        content: '海外の猫イベントや保護猫譲渡会で使える英会話。\n\n譲渡会（Adoption Event）：\n• "I\'m interested in adopting a cat."\n• "What\'s the adoption process like?"\n• "Do you have any senior cats?"（シニア猫はいますか？）\n\nボランティアに応募：\n• "I\'d like to volunteer. How can I help?"\n• "I can help with cleaning and feeding."\n• "I\'m good at taking photos for adoption profiles."\n\n猫コミュニティ：\n• "Are there any cat lover meetups in this area?"\n• "Do you have an Instagram for the shelter?"',
        vocab: [
          { en: 'adoption event', zh: '譲渡会', example: 'There\'s an adoption event this Saturday.' },
          { en: 'volunteer', zh: 'ボランティア', example: 'We\'re always looking for volunteers.' },
          { en: 'shelter', zh: '保護施設', example: 'The shelter takes care of 100+ cats.' },
          { en: 'foster fail', zh: '預かり失敗（里親になること）', example: 'We had a foster fail — we kept all three!' },
        ],
        quiz: [
          { q: '"adoption event" は何？', qZh: '', opts: ['猫の誕生日会', '譲渡会', '品評会', '運動会'], ans: 1 },
          { q: '"foster fail" の意味は？', qZh: '', opts: ['預かりの失敗（猫を返した）', '預かり失敗（結局里親になった）', '猫が逃げた', '病気になった'], ans: 1, explain: '"Foster fail" はポジティブな言葉！預かるつもりが愛着がわいて正式に里親になること。' },
        ],
      },
    ],
  },
];
